### ISSUE TITLE
Support Extra Big system font setting

### ISSUE THREAD

**Issue by ChristianTacke** [iNPUTmice/Conversations#2141]
#### General information

* **Version:** 1.14.9
* **Device:** Galaxy S4
* **Android Version:** 4.2
* **Server name:** self hosted
* **Conversations source:** F-Droid

#### Steps to reproduce

1. In system settings set font size to "Extra Large"
2. In Conversations enable "Large Fonts" in settings

#### Comments

Using the above settings, the font is still tiny. For visually impaired people (like me) this is still very hard to read. So it would be cool, if the "Extra Large" system font setting would be obeyd and increas font size even more.
Currently "Extra Large" has the same effect as "Large". According to a displayed notice on the device, apps have to support "Extra Large" explicitly. So it would be cool, if Conversations would support that.

**Comment by ChristianTacke** [comment]
Why close it? Has it been fixed in 2.x?

**Comment by licaon-kter** [comment]
Yes, we have 2 more sizes bigger than system.

If you're stuck on Android 4.3 or lower, then yes it's not fixed and it never will be.

**Comment by iNPUTmice** [comment]
@ChristianTacke if you point me to development resources that state how to support 'Extra Large' font setting I’m willing to implement that. However my google skills didn’t yield any results what so ever. (My device also doesn’t yield any such warning by the way.)

**Comment by ChristianTacke** [comment]
It's on Android 4.x. I think, I have found something on the internet about how to detect it a while back. It was about reading some settings directly or something strange.
Anyway: I haven't found something like that on 7.1.2. (which is a pity, because many things are way too small on 7.1.2. It's no fun for visually impaired people).

On 7.1.2 (LineageOS) there are two options to control sizing. One for font size one for display size. Setting both to max and enabling "large font" in Conversations (1.x still), makes the font nearly readable. Setting all three to minmum makes the font super tiny (I should ask a normal seeing person, whether they can read it).

Could you consider making the enlargement step of the in app option a bit bigger, so it makes more difference? People who want small fonts definitely have enough options to make fonts "unreadable".

**Comment by licaon-kter** [comment]
So you're on 7.1.2 now?

**Comment by ChristianTacke** [comment]
I have one device with 4.x and one with 7.1.2.
